URL = "https://archives.nseindia.com/content/historical/EQUITIES/"
ONE_MONTH_PATH = "DATA/1 MONTH"
FIVE_DAYS_PATH = "DATA/5 DAYS"
THREE_MONTHS_PATH = "DATA/3 MONTHS"
DIRECTORIES = [ONE_MONTH_PATH, FIVE_DAYS_PATH, THREE_MONTHS_PATH]
DATE_FORMAT = '%Y-%m-%d'
